server:
  port: ${port:8501}

spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}
  instance:
    hostname: ${hostname:eureka}
