server:
  port: ${port:8502}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8503/eureka/}

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${https://github.com/Tlsy/config-server.git}
          username: ${git.username:Tlsy}
          password: ${git.password:lsy4170937}
          search-paths: ${git.paths:*}