spring:
  application:
    name: cloud-admin

server:
  port: ${port:8505}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true

---
spring:
  profiles: docker
  application:
    name: cloud-admin

server:
  port: ${port:8505}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true
